### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by Bgmsquad1** [seb86/Attachment-Slug#7]
Can you please update the plugin for more compatibility to latest wordpress version

**Comment by seb86** [comment]
@Bgmsquad1 Is there any particular issue with the plugin you have seen? Seems to be working fine for me still.

**Comment by Bgmsquad1** [comment]
Yes its absolutely working fine and thanks for this amazing plugin.
Regarding update as it was last updated years ago. Just making sure if i can relay on for long term usage without any issues. :)

**Comment by seb86** [comment]
I've not seen any WordPress update that has interfered with how this plugin works but I will refresh the details to show the plugin is still actively working. Thank you for contacting.
