### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by Bgmsquad1** [seb86/Attachment-Slug#8]
Hey there,

I found a small issue, Hope it will be fixed soon.

I changed attachement slug to media where it looks like 

example.com/media/picture-1
But if media slug is removed it still shows the same content that is
example.com/picture-1

is there any fix that attachments should only be viewed with /media/ slug or it should return to homepage

**Comment by seb86** [comment]
This is not a bug @Bgmsquad1 

If the theme has an attachment page template then it will take you to that attachment page with or without this plugin. If the theme does not have a attachment page template, it will show the attachment link like so `http://made-by-seb-plugin-dev.local/?attachment_id=5` which redirects to the original attachment source.
